### ISSUE TITLE
Error: _create_or_update_package() got an unexpected keyword argument 'schema'

### ISSUE THREAD

**Issue by cfitz** [kata-csc/ckanext-oaipmh#3]
Hi, 
I got the error _create_or_update_package() got an unexpected keyword argument 'schema'
which is coming from : https://github.com/kata-csc/ckanext-oaipmh/blob/master/ckanext/oaipmh/harvester.py#L431-L435

There doesn't seem to be a named arg for this. Is there something I'm missing? 
I'm running on CKAN 2.4.

**Comment by juholehtonen** [comment]
Hi. We are using our own fork of ckanext-harvest with small adjustments: https://github.com/ckan/ckanext-harvest/compare/master...kata-csc:etsin-master#diff-5b0c56e24c391eb219cad921b2906b00
This is because we sometimes allow more relaxed data validations while harvesting compared to inserting/viewing data in web user interface.

We use CKAN 2.5.2, not sure if still 2.4 works.
